### ISSUE TITLE
No icon in URL address bar to click on

### ISSUE THREAD

**Issue by fordag** [yoichiro/image_collector_extension#1]
I'm attempting to collect images from two websites:
http://luvfireimages.smugmug.com/FIRE-APPARATUS
http://www.smokeyshots.com/

When I go to either website there is no framed image in the URL bar to click on to download the images.

**Comment by yoichiro** [comment]
Image Collector extension has some configuration preferences to change behaviors of each function. You can visit the page to configure them from the extension page: chrome://extensions/
As the default setting, a file name of target images which are fetched by this extension must have a ".jpeg" or ".jpg" suffix. The file name of iImages on your URLs doesn't have such extensions. If you change the setting for its suffix, then you will be able to fetch them, I think.
