### ISSUE TITLE
gateway timeout

### ISSUE THREAD

**Issue by hussein99** [yoichiro/image_collector_extension#3]
Hi there,
The extension is great many thanks. It used to work just fine, but now when you click on the top right corner on the icon, the picture does not appear for a long time, and then when it does, the picture is fine but the bottom advert part says gateway time out. So i think the cause of the delay is the adverts in the extension. Please have a look at this as soon as possible. Your help is much appreciated.
![untitled](https://cloud.githubusercontent.com/assets/11910119/7105307/094e3240-e10a-11e4-8408-a5cd2c636fd4.jpg)

**Comment by yoichiro** [comment]
@hussein99 Sorry, my Web server was hung-up. I restarted the server.
